sonar.projectKey=alexwang66_apptrust-workshop
sonar.organization=alexwang66
sonar.projectName=AppTrust Workshop
sonar.sources=app,scripts,governance
sonar.tests=test,tests
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
sonar.sourceEncoding=UTF-8
